### ISSUE TITLE
Upload.php not working

### ISSUE THREAD

**Issue by UriX-Technology** [mrknorton4007/sabre-file-manager#3]
Sir
Thanks for the code thus far but when I click on the upload button nothing happens.

Thanks for your help

Regards

**Comment by mrknorton4007** [comment]
Hi Uriel1988,
as you may have seen, this project is in a some kind of limbo. Can I ask you what browser and what OS are you using?
Clicking the upload button should trigger the "open file" window of your browser.

Also, are you sure that a folder named like the `sb_file_path` param exists?

**Comment by UriX-Technology** [comment]
Thanks Sir. Your project is fantastic. Issue solved. However, I actually wanted it for job board as I have check the entire internet and could not find something simple.
